### ISSUE TITLE
The pgpwordlist package needs a README.md

### ISSUE THREAD

**Issue by davecgh** [decred/dcraddrgen#3]
For consistency, and to be in line with the project guidelines, the `pgpwordlist` package needs a `README.md` and `doc.go`.

**Comment by jcvernaleo** [comment]
As I said for #4 I agree, but this is only here temporarily.  Once dcrwallet is released this code will be deleted and imported from there.

**Comment by davecgh** [comment]
Right, that makes sense.  I didn't realize it was temporary code.  Closing.
