### ISSUE TITLE
The chainhash package needs a README.md

### ISSUE THREAD

**Issue by davecgh** [decred/dcraddrgen#4]
For consistency, and to be in line with the project guidelines, the `chainhash` package needs a `README.md` and `doc.go`.

**Comment by jcvernaleo** [comment]
Agreed, but chainhash is only included in this package until we release the code for dcrd.  At that point I will update dcraddrgen to import chainhash from dcrd (where it will have the proper files added) and the local copy of this will be deleted.

**Comment by davecgh** [comment]
Right, that makes sense.  I didn't realize it was temporary code.  Closing.
